version: "3.8"

services:
  server: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_DATABASE_NAME: prisma_dev_db
      PRISMA_DATABASE_URL: mysql://root:root@mysql:3306/prisma_dev_db?schema=public
    ports:
      - 1776:1776
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
    depends_on:
      - mysql
    networks:
      - prisma_dev_network



  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - prisma_dev_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - prisma_dev_network


volumes:
  mysql_data:
    driver: local

networks:
  prisma_dev_network:
    driver: bridge
    name: prisma_dev_network