version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile #specify Dockerfile to run
    ports:
      - '1886:1886'
    volumes:
      - /app/node_modules #It means do not try map a folder up against app/node_modules
      - .:/app #map outside of container to the folder inside of container
