version: '3.7'

services: 
  main: 
    container_name: nestjs-postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '1776:1776'
    command: yarn start:dev
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - webnet
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
  
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


networks:
  webnet:
volumes:
  postgres:
    name: nest-db