language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tienduynguyen/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -it tienduynguyen/multi-docker-test yarn test --coverage

branches:
  only:
    - main
after_success:
  - docker build -t tienduynguyen/multi-client ./client
  - docker build -t tienduynguyen/multi-nginx ./nginx
  - docker build -t tienduynguyen/multi-server ./server
  - docker build -t tienduynguyen/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tienduynguyen/multi-client
  - docker push tienduynguyen/multi-nginx
  - docker push tienduynguyen/multi-server
  - docker push tienduynguyen/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  bucket_name: $AWS_BUCKER_NAME
  bucket_path: multi-docker
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
