version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-calculator
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=calculator_db
      - POSTGRES_PORT=5432

  redis:
    image: redis:latest
    container_name: redis-calculator
  nginx:
    container_name: nginx-calculator
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # a command for not try to overwrite this folder
      - ./server:/app # see the default documentation for redis & postgres at https://hub.docker.com/
    container_name: server_calculator
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # default redis port
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=calculator_db
      - POSTGRES_PORT=5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    container_name: worker_calculator
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client_calculator
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
